### ISSUE TITLE
Improve background sorting and naming

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-ios#138] opened 2015-07-30 12:38 UTC
Currently the backgrounds are named "012015" etc. and sorted alphabetically by this. They should instead be sorted by year and then month. Resulting in the most recent backgrounds at the top. Additionally they should be formatted according to the selected language locale on the device.

**Comment by revolter** [comment] 2015-10-06 08:57
Why not name them `201501` and the sorting will work as intended.

**Comment by vIiRuS** [comment] 2015-10-06 09:22
The names are provided by the api and the values are stored in the database and used on the website. Changing the naming could cause a lot of pain.

Having a custom serialized field for sorting might be an idea though. Haven't thought about that before.

**Comment by revolter** [comment] 2015-10-06 09:34
Well, a simple regex could split it so it could be saved in 2 columns (like it should) so sorting should be easier.

**Comment by vIiRuS** [comment] 2015-10-06 09:52
something like that was my idea. (although 1 column might be better/enough). So that it has both a "key" and a "sortedkey" column. the first is used for uniqueness and communication with the api and the latter is used for sorting during display and has the flipped key

**Comment by revolter** [comment] 2015-10-06 10:03
[Regex example](https://regex101.com/r/wM2kF8/1).
[Objective C implementation example](http://goo.gl/MPyoJt).

You should consider adding [Objective C RegEx Categories](https://github.com/bendytree/Objective-C-RegEx-Categories) into the project to simplify regexes and increase readability. I have personally used it with great success.

**Comment by vIiRuS** [comment] 2015-10-06 10:09
As this would involve changes to the database structure, I'll do this change once I merged the `1.1` branch back in (which I'll do the next days).
I'll also look into the RegEx Categories project. Thanks!

**Closed** 2018-06-13 15:52 UTC
Labels: Priority: minor, Type: Enhancement
