### ISSUE TITLE
Problem with list ordering

### ISSUE THREAD

**Issue by sdale28** [HabitRPG/habitica-ios#410] opened 2016-10-02 21:37 UTC
Hi there. I've been having problems with my ToDo List when I reorder items. There is an issue listed on the main HabitRPG (https://github.com/HabitRPG/habitrpg/issues/8075) but I just wanted to make a note that I'm experiencing problems within the iOS app. 

For example if I had the following list:
1. Todo1
2. Todo2

Then I add a new item:
1. Todo3
2. Todo1
3. Todo2

When I try and rearrange it to this:
1. Todo1
2. Todo2
3. Todo3

Usually this is what happens once I let go of Todo3 in slot 3:
1. Todo1
2. Todo1
3. Todo2

If I pull down on the list to refresh the list and then close the app, the next time I open the app, the list will be in the correct order (also, multiple refreshes doesn't help): 
1. Todo1
2. Todo2
3. Todo3

I'm not an iOS programmer yet, but my best guess is that the GET is happening faster than the POST to the server, causing the wrong order to show up. Then when the app is forced to reload from the server, everything is reset and fine. 

User-ID: 8fe24168-e547-4f24-a46e-2dddc0266ca2

Cheers!

**Comment by vIiRuS** [comment] 2016-11-09 13:00
Having trouble reproducing this. is it possible that depending on how fast you do these actions makes a difference? Does it also happen when you wait a bit between creating a task and moving it?

**Comment by sdale28** [comment] 2016-11-15 19:32
A little bit. It’s more like when I do batches of To-Do’s (check off a few and add several) at once, then things start showing up in weird places (old ones duplicated, order wrong). It’s especially bad if I rearrange the To-Do’s during this process to get them in the order that I want. I’ve found that if I go to Settings > Clear Cache and then Reload Content, everything comes back in the right order.

**Comment by LutherZhao** [comment] 2017-09-27 21:45
I am experiencing this problem as well, and I notice it happens when you add at least 2 tasks, and then try to rearrange the newly added tasks:

1. have some to-dos in a list already
2. add a to-do, call it test1
3. add another to-do, call it test2
4. re-arrange the position of test2 to somewhere in the middle of the to-do list 

Bug: test2 does not stay in the newly arranged place, I need to close the app and relaunch, and then re-arrange, for the re-arrange to stick
Bug2: test1 appears twice in the list (this goes away if I go to another view and come back, or simply scroll it out of view and scroll back, which suggests to me the tableviewcell text field became stale). 

Bug3: Lastly, if i try to delete test2 (after rearranging without restarting), it crashes

This bug affects all checklists (habit, dailies, todo)

**Comment by saraolson** [comment] 2017-11-27 22:12
I'm going to add this til 1.12 milestone since we're taking on task reordering problems then

**Closed** 2018-01-07 13:00 UTC
Labels: Priority: medium, Type: Bug

**Comment by Blaisorblade** [comment] 2018-01-19 11:30
I have 1.12, the App Store notice claims the bug is fixed, and it isn’t. I have tons of tasks, I trigger this to do 2-3 reorderings in a row to get the bug. Refreshing the task list from the server changes the result but doesn’t fix the bug, I have to force close and reload to remove the duplication — and I don’t think I necessarily get the order I asked for.

Here’s a screenshot (where I’ve blacked out identifying information) — those 5 are copies of the same task.

![d785aa1f-6569-4fda-8e41-f1a2d625ee1d](https://user-images.githubusercontent.com/289960/35148797-f7350722-fd13-11e7-8c51-82175f985903.jpeg)

**Comment by phillipthelen** [comment] 2018-01-19 13:41
Which iOS version do you have? I can‘t reproduce this issue anymore

-- 
Phillip Thelen
Sent with Airmail

**Comment by Blaisorblade** [comment] 2018-01-19 13:46
iOS 11.2.2 (latest), iPad Pro 10,5’’ 2017.
